/**
 * Legal Safety Framework & Principles for LawGuide AI.
 *
 * Defines explicit boundaries, guardrails, and classification constants
 * to ensure the platform assists users without providing unauthorized legal practice (UPL)
 * or misleading legal declarations.
 */

export const LEGAL_DISCLAIMERS = {
  GLOBAL_FOOTER:
    'LawGuide AI provides legal information and document analysis tools, not legal advice. The platform does not form an attorney-client relationship and should not substitute for consultation with a licensed attorney.',
  ANALYSIS_BANNER:
    'This analysis is generated by AI to help you understand your document. While grounded in the text, you should verify all critical terms with a qualified legal professional before signing or making legal decisions.',
  COMPARISON_BANNER:
    'Comparison highlights differences between provided document versions. Subtle nuances may exist; always review with professional counsel for material transactions.',
  EVIDENCE_GROUNDING:
    'All factual statements are anchored to specific excerpts within your uploaded document. Click citations to view the verified source text.',
} as const;

/**
 * Classification types for all AI-generated assertions.
 * Every piece of analysis must be tagged with one of these types.
 */
export const EVIDENCE_SOURCE_TYPES = {
  DOCUMENT_FACT: 'DOCUMENT_FACT',
  AI_INTERPRETATION: 'AI_INTERPRETATION',
  GENERAL_INFO: 'GENERAL_INFO',
  NEEDS_REVIEW: 'NEEDS_REVIEW',
  USER_PROVIDED: 'USER_PROVIDED',
} as const;

export type EvidenceSourceType = (typeof EVIDENCE_SOURCE_TYPES)[keyof typeof EVIDENCE_SOURCE_TYPES];

export interface EvidenceClassificationMetadata {
  type: EvidenceSourceType;
  label: string;
  description: string;
  badgeVariant: 'success' | 'info' | 'warning' | 'neutral';
}

export const EVIDENCE_CLASSIFICATIONS: Record<EvidenceSourceType, EvidenceClassificationMetadata> = {
  [EVIDENCE_SOURCE_TYPES.DOCUMENT_FACT]: {
    type: EVIDENCE_SOURCE_TYPES.DOCUMENT_FACT,
    label: 'Document Fact',
    description: 'Directly stated in the document text with verifiable citation.',
    badgeVariant: 'success',
  },
  [EVIDENCE_SOURCE_TYPES.AI_INTERPRETATION]: {
    type: EVIDENCE_SOURCE_TYPES.AI_INTERPRETATION,
    label: 'AI Interpretation',
    description: 'Plain-language synthesis or inferred meaning derived from document clauses.',
    badgeVariant: 'info',
  },
  [EVIDENCE_SOURCE_TYPES.GENERAL_INFO]: {
    type: EVIDENCE_SOURCE_TYPES.GENERAL_INFO,
    label: 'General Legal Info',
    description: 'Educational explanation of standard legal terms, principles, or statutory concepts.',
    badgeVariant: 'neutral',
  },
  [EVIDENCE_SOURCE_TYPES.NEEDS_REVIEW]: {
    type: EVIDENCE_SOURCE_TYPES.NEEDS_REVIEW,
    label: 'Needs Professional Review',
    description: 'Ambiguous, high-risk, or non-standard language requiring lawyer review.',
    badgeVariant: 'warning',
  },
  [EVIDENCE_SOURCE_TYPES.USER_PROVIDED]: {
    type: EVIDENCE_SOURCE_TYPES.USER_PROVIDED,
    label: 'User Provided Context',
    description: 'Information, consultation goals, or notes supplied directly by the user.',
    badgeVariant: 'neutral',
  },
};

/**
 * Permitted capabilities and mandatory behavioral constraints.
 */
export const LEGAL_GUARDRAILS = {
  ALLOWED_CAPABILITIES: [
    'Document summarization and structure breakdown',
    'Clause and obligation identification',
    'Plain-language explanation of complex legalese',
    'Side-by-side document diffing and change tracking',
    'Question generation for consultations with licensed counsel',
    'Checklists of items to verify or clarify',
    'Evidence grounding with page and paragraph citations',
    'General educational explanations of legal concepts and common practices',
    'Authoritative statutory and legal-aid navigation assistance',
  ],
  STRICTLY_PROHIBITED: [
    'Claiming or implying attorney status or an attorney-client relationship',
    'Declaring any contract or clause definitively illegal or unenforceable',
    'Predicting judicial or arbitration outcomes',
    'Advising whether a party should sue, settle, or breach a contract',
    'Fabricating legal case citations or statutory authorities (anti-hallucination)',
    'Inventing facts or citations not present in the user-provided document',
    'Inferring jurisdiction from IP, browser location, currency, or language',
    'Merging document facts and general legal information invisibly',
  ],
} as const;

/**
 * Explicit operational modes for the Legal Information Navigator (Phase 7).
 */
export const LEGAL_INFO_MODES = {
  MY_DOCUMENT: 'MY_DOCUMENT',
  GENERAL_LEGAL_INFO: 'GENERAL_LEGAL_INFO',
  PREPARE_FOR_COUNSEL: 'PREPARE_FOR_COUNSEL',
} as const;

export type LegalInfoMode = (typeof LEGAL_INFO_MODES)[keyof typeof LEGAL_INFO_MODES];

/**
 * Jurisdiction provenance classification.
 */
export const JURISDICTION_SOURCE_TYPES = {
  DOCUMENT_JURISDICTION: 'DOCUMENT_JURISDICTION',
  USER_PROVIDED_JURISDICTION: 'USER_PROVIDED_JURISDICTION',
  JURISDICTION_NOT_ESTABLISHED: 'JURISDICTION_NOT_ESTABLISHED',
} as const;

export type JurisdictionSourceType =
  (typeof JURISDICTION_SOURCE_TYPES)[keyof typeof JURISDICTION_SOURCE_TYPES];

/**
 * Source authority / trust levels.
 */
export const SOURCE_TRUST_LEVELS = {
  PRIMARY: 'PRIMARY',
  SECONDARY: 'SECONDARY',
  GENERAL: 'GENERAL',
} as const;

export type SourceTrustLevel = (typeof SOURCE_TRUST_LEVELS)[keyof typeof SOURCE_TRUST_LEVELS];

/**
 * Prohibited definitive legal conclusions (anti-UPL guardrail).
 */
export const PROHIBITED_LEGAL_CONCLUSIONS = [
  /\bthis clause is illegal\b/i,
  /\bthis contract is (definitively )?invalid\b/i,
  /\bthis clause is (definitively )?unenforceable\b/i,
  /\byou are legally required to\b/i,
  /\byou will win\b/i,
  /\byou should sue\b/i,
  /\byou should (sign|reject) this\b/i,
  /\byou definitely have a case\b/i,
  /\bdocument [a-z0-9_-]+ (overrides|supersedes|cancels) document [a-z0-9_-]+\b/i,
  /\bthis (document|agreement|amendment) takes precedence\b/i,
  /\bthis amendment is (legally )?valid\b/i,
];

/**
 * Matter document role classification.
 */
export const MATTER_DOCUMENT_ROLES = {
  PRIMARY_AGREEMENT: 'PRIMARY_AGREEMENT',
  REVISED_AGREEMENT: 'REVISED_AGREEMENT',
  AMENDMENT: 'AMENDMENT',
  NOTICE: 'NOTICE',
  POLICY: 'POLICY',
  ANNEXURE: 'ANNEXURE',
  SUPPORTING_DOCUMENT: 'SUPPORTING_DOCUMENT',
  OTHER: 'OTHER',
} as const;

export type MatterDocumentRole =
  (typeof MATTER_DOCUMENT_ROLES)[keyof typeof MATTER_DOCUMENT_ROLES];

/**
 * Cross-document relationship classification.
 */
export const DOCUMENT_RELATIONSHIP_TYPES = {
  REFERENCES: 'REFERENCES',
  AMENDS: 'AMENDS',
  INCORPORATES: 'INCORPORATES',
  ATTACHES: 'ATTACHES',
  MENTIONS: 'MENTIONS',
  DATES_BACK_TO: 'DATES_BACK_TO',
  RELATED_TO: 'RELATED_TO',
} as const;

export type DocumentRelationshipType =
  (typeof DOCUMENT_RELATIONSHIP_TYPES)[keyof typeof DOCUMENT_RELATIONSHIP_TYPES];

/**
 * Cross-document consistency observation categories.
 */
export const CONSISTENCY_CATEGORIES = {
  DATES: 'DATES',
  PARTIES: 'PARTIES',
  NOTICE: 'NOTICE',
  PAYMENT: 'PAYMENT',
  TERM: 'TERM',
  TERMINATION: 'TERMINATION',
  GOVERNING_LAW: 'GOVERNING_LAW',
  LIABILITY: 'LIABILITY',
  CONFIDENTIALITY: 'CONFIDENTIALITY',
  DEFINED_TERMS: 'DEFINED_TERMS',
  DOCUMENT_REFERENCES: 'DOCUMENT_REFERENCES',
  DISPUTE_RESOLUTION: 'DISPUTE_RESOLUTION',
  OTHER: 'OTHER',
} as const;

export type ConsistencyCategory =
  (typeof CONSISTENCY_CATEGORIES)[keyof typeof CONSISTENCY_CATEGORIES];

/**
 * Checks whether text contains prohibited legal advice verdicts.
 */
export function containsProhibitedLegalConclusion(text: string): boolean {
  return PROHIBITED_LEGAL_CONCLUSIONS.some((pattern) => pattern.test(text));
}

/**
 * Phase 9: Matter Action Item Types
 */
export const ACTION_ITEM_TYPES = {
  REVIEW_DOCUMENT: 'REVIEW_DOCUMENT',
  REQUEST_DOCUMENT: 'REQUEST_DOCUMENT',
  VERIFY_FACT: 'VERIFY_FACT',
  VERIFY_TERM: 'VERIFY_TERM',
  PROVIDE_MISSING_INFORMATION: 'PROVIDE_MISSING_INFORMATION',
  COLLECT_DOCUMENT: 'COLLECT_DOCUMENT',
  REVIEW_TIMELINE: 'REVIEW_TIMELINE',
  REVIEW_CONSISTENCY: 'REVIEW_CONSISTENCY',
  RESOLVE_DISCREPANCY: 'RESOLVE_DISCREPANCY',
  ASK_COUNSEL: 'ASK_COUNSEL',
  CONFIRM_USER_CONTEXT: 'CONFIRM_USER_CONTEXT',
  FOLLOW_UP: 'FOLLOW_UP',
  GENERAL_INFORMATION: 'GENERAL_INFORMATION',
} as const;

export type ActionItemType = (typeof ACTION_ITEM_TYPES)[keyof typeof ACTION_ITEM_TYPES];

export const ACTION_ITEM_STATUSES = {
  OPEN: 'OPEN',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  DISMISSED: 'DISMISSED',
} as const;

export type ActionItemStatus = (typeof ACTION_ITEM_STATUSES)[keyof typeof ACTION_ITEM_STATUSES];

export const ACTION_ITEM_PRIORITIES = {
  HIGH: 'HIGH',
  MEDIUM: 'MEDIUM',
  LOW: 'LOW',
  INFORMATIONAL: 'INFORMATIONAL',
} as const;

export type ActionItemPriority = (typeof ACTION_ITEM_PRIORITIES)[keyof typeof ACTION_ITEM_PRIORITIES];

export const ACTION_ITEM_SOURCE_TYPES = {
  DOCUMENT: 'DOCUMENT',
  LEGAL_XRAY: 'LEGAL_XRAY',
  COMPARISON: 'COMPARISON',
  RELATIONSHIP: 'RELATIONSHIP',
  CONSISTENCY: 'CONSISTENCY',
  TIMELINE: 'TIMELINE',
  MISSING_INFO: 'MISSING_INFO',
  MATTER_WORKSPACE: 'MATTER_WORKSPACE',
  USER_NOTE: 'USER_NOTE',
  USER_CREATED: 'USER_CREATED',
  MANUAL: 'MANUAL',
} as const;

export type ActionItemSourceType =
  (typeof ACTION_ITEM_SOURCE_TYPES)[keyof typeof ACTION_ITEM_SOURCE_TYPES];

/**
 * Strict date provenance classifications.
 */
export const DATE_PROVENANCE_TYPES = {
  DOCUMENT_STATED: 'DOCUMENT_STATED',
  USER_PROVIDED: 'USER_PROVIDED',
  CALCULATED_EXPLICIT: 'CALCULATED_EXPLICIT',
} as const;

export type DateProvenanceType =
  (typeof DATE_PROVENANCE_TYPES)[keyof typeof DATE_PROVENANCE_TYPES];

/**
 * Matter activity audit log types.
 */
export const MATTER_ACTIVITY_TYPES = {
  DOCUMENT_ATTACHED: 'DOCUMENT_ATTACHED',
  DOCUMENT_DETACHED: 'DOCUMENT_DETACHED',
  ROLE_UPDATED: 'ROLE_UPDATED',
  RELATIONSHIPS_SCANNED: 'RELATIONSHIPS_SCANNED',
  RELATIONSHIP_CONFIRMED: 'RELATIONSHIP_CONFIRMED',
  RELATIONSHIP_REJECTED: 'RELATIONSHIP_REJECTED',
  CONSISTENCY_CHECKED: 'CONSISTENCY_CHECKED',
  NOTE_ADDED: 'NOTE_ADDED',
  NOTE_DELETED: 'NOTE_DELETED',
  ACTION_ITEM_CREATED: 'ACTION_ITEM_CREATED',
  ACTION_ITEM_UPDATED: 'ACTION_ITEM_UPDATED',
  ACTION_ITEM_DELETED: 'ACTION_ITEM_DELETED',
  ACTION_ITEM_COMPLETED: 'ACTION_ITEM_COMPLETED',
  ACTION_ITEMS_GENERATED: 'ACTION_ITEMS_GENERATED',
  PREPARATION_BRIEF_GENERATED: 'PREPARATION_BRIEF_GENERATED',
  EVIDENCE_REVIEWED: 'EVIDENCE_REVIEWED',
  EVIDENCE_LEDGER_VIEWED: 'EVIDENCE_LEDGER_VIEWED',
  CITATION_VERIFICATION_RUN: 'CITATION_VERIFICATION_RUN',
} as const;

export type MatterActivityType =
  (typeof MATTER_ACTIVITY_TYPES)[keyof typeof MATTER_ACTIVITY_TYPES];

/**
 * Phase 10: Normalized Evidence Types
 */
export const EVIDENCE_TYPES = {
  DOCUMENT_FACT: 'DOCUMENT_FACT',
  COMPARISON_EVIDENCE: 'COMPARISON_EVIDENCE',
  RELATIONSHIP_EVIDENCE: 'RELATIONSHIP_EVIDENCE',
  CONSISTENCY_EVIDENCE: 'CONSISTENCY_EVIDENCE',
  TIMELINE_EVIDENCE: 'TIMELINE_EVIDENCE',
  PREPARATION_EVIDENCE: 'PREPARATION_EVIDENCE',
  USER_PROVIDED: 'USER_PROVIDED',
  GENERAL_INFORMATION: 'GENERAL_INFORMATION',
  AI_INTERPRETATION: 'AI_INTERPRETATION',
  NEEDS_REVIEW: 'NEEDS_REVIEW',
} as const;

export type EvidenceType = (typeof EVIDENCE_TYPES)[keyof typeof EVIDENCE_TYPES];

export const VERIFICATION_STATUSES = {
  VERIFIED: 'VERIFIED',
  NEEDS_REVIEW: 'NEEDS_REVIEW',
  UNVERIFIED: 'UNVERIFIED',
} as const;

export type VerificationStatus =
  (typeof VERIFICATION_STATUSES)[keyof typeof VERIFICATION_STATUSES];

export const CONFIDENCE_CATEGORIES = {
  HIGH: 'HIGH',
  MEDIUM: 'MEDIUM',
  LOW: 'LOW',
  UNVERIFIED: 'UNVERIFIED',
} as const;

export type ConfidenceCategory =
  (typeof CONFIDENCE_CATEGORIES)[keyof typeof CONFIDENCE_CATEGORIES];

/**
 * System safety instructions injected into AI prompt orchestrators.
 */
export const SYSTEM_SAFETY_DIRECTIVE = `
CRITICAL LEGAL SAFETY RULES:
1. You are LawGuide AI, a document analysis assistant. You are NOT an attorney.
2. NEVER declare a clause "illegal", "invalid", or "unenforceable". Instead, state: "This clause uses unusual or restrictive terms that an attorney should review."
3. NEVER advise users whether to sign, sue, accept, or breach an agreement.
4. Ground every document fact in verifiable text excerpts from the provided document.
5. If the document does not contain sufficient information to answer a question, explicitly state: "The provided document does not mention or specify this."
6. Classify every finding into: DOCUMENT_FACT, AI_INTERPRETATION, GENERAL_INFO, NEEDS_REVIEW, or USER_PROVIDED.
7. Always clearly distinguish what the user's specific document says from general legal educational information.
8. For cross-document analysis: NEVER decide which document or contract controls, wins, or takes legal precedence. Report apparent differences neutrally as discussion points for counsel.
9. Never recommend legal strategies, litigation decisions, settlement amounts, or whether to sue, settle, sign, or terminate. Action items must be neutral organizational preparation tasks, never legal strategy instructions.
10. Evidence Traceability: Ground all claims in exact, verifiable quotes and page numbers. Clearly label whether information is verified from a document, general educational information, AI interpretation, or user-provided context. Never fabricate citations or promote unverified claims into document facts.
`.trim();



